#Define variables
JC = javac
SRC_DIR = src
BIN_DIR = bin
MAIN_CLASS = TokTik

# Find all .java files in the src directory
SOURCES := $(wildcard $(SRC_DIR)/*.java)

# Generate corresponding .class file names
CLASSES := $(patsubst $(SRC_DIR)/%.java,$(BIN_DIR)/%.class,$(SOURCES))

# Define the build target
all: $(CLASSES)

#Define how to build .class files from .java files
$(BIN_DIR)/%.class: $(SRC_DIR)/%.java
	@mkdir -p $(@D)
	$(JC) - cp $(BIN_DIR) -d $(BIN_DIR) $<

#Define the run target
TokTik: bin/TokTik.class
	java -cp bin TokTik
run:
	java - cp $(BIN_DIR) $(MAIN_CLASS)
	
#Define the clean target
clean:
	rm -rf $(BIN_DIR)

.PHONY: all run clean
