JAVAC=/usr/bin/javac
.SUFFIXES: .java .class
SRCDIR=src
BINDIR=bin

$(BINDIR)/%.class:$(SRCDIR)/%.java
	$(JAVAC) -d $(BINDIR)/ -cp $(BINDIR) $<
	
CLASSES=Vaccine.class \
	Account.class \
	BinaryTreeNode.class \
	BTQueueNode.class \
	BTQueue.class \
	BinaryTree.class \
    BTQueueNode.class \
	BinarySearchTree.class \
	JTextAreaOutputStream.class \
	MyGUI.class \
	Post.class \
	TokTik.class \
	TokTikUtility.class
                 
CLASS_FILES=$(CLASSES:%.class=$(BINDIR)/%.class)

default: $(CLASS_FILES)

clean:
	rm $(BINDIR)/*.class
run: $(CLASS_FILES)
	java -cp bin TokTik
	
bst: $(CLASS_FILES)
	java -cp bin TokTik